/**
 * Created by zwt on 2018/12/24.
 */

var GROUP_CONF = [
    {
        key:'cfg_rssi_threshold',
        value:-95,
        des:lang['cfg_rssi_threshold']
    },
    {
        key:'cfg_plos_threshold',
        value:-3,
        des:lang['cfg_plos_threshold']
    },
    {
        key:'cfg_tof_0d_threshold',
        value: 5,
        des:lang['cfg_tof_0d_threshold']
    },
    {
        key:'cfg_rxFP_threshold',
        value:35,
        des:lang['cfg_rxFP_threshold']
    },
    {
        key:'cfg_IDiff_threshold',
        value:400,
        des:lang['cfg_IDiff_threshold']
    },
    {
        key:'cfg_mc_threshold',
        value:10,
        des:lang['cfg_mc_threshold']
    },
    {
        key:'cfg_plos_is_no_filter',
        value:0,
        des:lang['cfg_plos_is_no_filter']
    },
    {
        key:'cfg_tof_offset',
        value:0,
        des:lang['cfg_tof_offset']
    },
    {
        key:'cfg_no_master_group',
        value:0,
        des:lang['cfg_no_master_group']
    },
    {
        key:'cfg_master_group_zone_id',
        value:0,
        des:lang['cfg_master_group_zone_id']
    },
    {
        key:'cfg_tdoa1d_width',
        value:1.2,
        des:'一维定位区域宽度'
    },
    {
        key:'cfg_x_offset',
        value:0,
        des:lang['cfg_x_offset']
    },
    {
        key:'cfg_y_offset',
        value:0,
        des:lang['cfg_y_offset']
    },
    {
        key:'cfg_rate_offset',
        value:0,
        des:lang['cfg_rate_offset']
    },
    {
        key:'cfg_forceSelectAlone',
        value:0,
        des:lang['cfg_forceSelectAlone']
    },
];