
#======================================#
#========== Project settings ==========#
#======================================#

# 产品或项目名称、软件开发公司名称
productName: 医废智慧平台
companyName: 山东荣登信息技术有限公司

# 产品版本、版权年份
productVersion:
copyrightYear:

#是否演示模式
demoMode: false

#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8980
  context-path: /
  tomcat:
    uri-encoding: UTF-8

#======================================#
#========== Database sttings ==========#
#======================================#

# 数据库连接
jdbc:

  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/wastemanage?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: 51Topping.com
  testSql: SELECT 1

  #  # Oracle 数据库配置
  #  type: oracle
  #  driver: oracle.jdbc.driver.OracleDriver
  #  url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
  #  username: jeesite
  #  password: jeesite
  #  testSql: SELECT 1 FROM DUAL

  #  # Sql Server 数据库配置
  #  type: mssql
  #  driver: net.sourceforge.jtds.jdbc.Driver
  #  url: jdbc:jtds:sqlserver://127.0.0.1:1433/jeesite
  #  username: jeesite
  #  password: jeesite
  #  testSql: SELECT 1

  #  # PostgreSql 数据库配置（注意：一定要创建的schema与username相同，否则将找不到数据表字典信息）
  #  type: postgresql
  #  driver: org.postgresql.Driver
  #  url: jdbc:postgresql://127.0.0.1:5432/jeesite
  #  username: jeesite
  #  password: jeesite
  #  testSql: SELECT 1

  #  # 连接信息加密
  #  encrypt:
  #
  #    # 加密连接用户名
  #    username: false
  #    # 加密连接密码
  #    password: true
  #
  #  # 数据库连接池配置
  #  pool:
  #
  #    # 初始化连接数
  #    init: 1
  #    # 最小连接数
  #    minIdle: 3
  #    # 最大连接数
  #    maxActive: 20

  #  # 多数据源名称列表，启用方式：@MyBatisDao(dataSourceName="ds2")
  #  dataSourceNames: ds2
  #
  #  # 多数据源配置：ds2
  #  ds2:
  #    type: oracle
  #    driver: oracle.jdbc.driver.OracleDriver
  #    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
  #    username: jeesite
  #    password: jeesite
  #    testSql: SELECT 1 FROM DUAL
  #    encrypt:
  #      username: false
  #      password: true
  #    pool:
  #      init: 1
  #      minIdle: 3
  #      maxActive: 20

#  # JTA 分布式事务（v4.0.4+）
#  jta:
#    enabled: false

#  # 表名前缀
#  tablePrefix: js_

#  # Druid连接池监控
#  druid:
#    stat:
#      enabled: true


# Redis 配置
#redis:
#  enabled: false
#
#  # Redis 连接参数
#  host: 127.0.0.1
#  port: 6379
#  isSSL: false
#  timeout: 2000
#  password: 1234
#  database: 0
#  clientName: ~
#
#  # Redis 连接池配置
#  pool:
#    maxIdle: 3
#    maxTotal: 20
#
#  # 是否启用Redis系统缓存及会话（专业版）
#  cacheAndSession: false
#
#  # 定义Key的前缀标识
#  keyPrefix: ${jdbc.tablePrefix}

# 微信appid,secret
wechat:
  mp:
    appId: wxe6834ce5cfa154ad
    secret: e78764f0daff4e421f25e26369d5948c
